package com.technokratos;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class Main {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test2() {
        driver.get("https://ion-inf.cloudtext.ru/login");
        driver.manage().window().setSize(new Dimension(1067, 616));
        driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control")).sendKeys("vrsick666@gmail.com");
        driver.findElement(By.cssSelector(".btn")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-control")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(6) > .form-control")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(6) > .form-control")).sendKeys("vrsick666");
        driver.findElement(By.cssSelector(".btn")).click();
    }
}
